/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "placesairports.h"

bool_t
xdr_airportslist (XDR *xdrs, airportslist *objp)
{
	register int32_t *buf;

	 if (!xdr_pointer (xdrs, (char **)objp, sizeof (struct airportsnode), (xdrproc_t) xdr_airportsnode))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_airportsnode (XDR *xdrs, airportsnode *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->code, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->name, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->state, ~0))
		 return FALSE;
	 if (!xdr_float (xdrs, &objp->distance))
		 return FALSE;
	 if (!xdr_airportslist (xdrs, &objp->next))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_coordinates (XDR *xdrs, coordinates *objp)
{
	register int32_t *buf;

	 if (!xdr_float (xdrs, &objp->lattitude))
		 return FALSE;
	 if (!xdr_float (xdrs, &objp->longitude))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_readairports_ret (XDR *xdrs, readairports_ret *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->err))
		 return FALSE;
	switch (objp->err) {
	case 0:
		 if (!xdr_airportslist (xdrs, &objp->readairports_ret_u.list))
			 return FALSE;
		break;
	case 1:
		break;
	default:
		return FALSE;
	}
	return TRUE;
}
