/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "places.h"
#include "trie.h"
#include "airports.h"

readplaces_ret *
get_places_1_svc(struct location *argp, struct svc_req *rqstp)
{
	static readplaces_ret  result;
	
	
	trieNode_t *search_result;
	placeslist * list;	
	char place_name[66];
	placeslist temp;
	int i = 0;
	
	//strcat(place_name, argp->state);
	//strcat(place_name, argp->city);

	//xdr_free((xdrproc_t)xdr_readplaces_ret, (char *)&result.readplaces_ret_u.list);
	
	//list = &result.readplaces_ret_u.list;

	char merge[255];
	strcpy(merge, argp->state);
	strcat(merge, argp->city);

	//strcat(place_name, p->name);
	//printf("Place_Name: %s", place_name);
	for (i = 0; merge[i]; i++)
	  {
		merge[i] = tolower(merge[i]);
	  }

	
	//printf("Merged: %s\n", merge);
	
	search_result = TrieSearchPartial(root->children,merge);

	// found places now make a call to airport_server
	if (search_result) {
	  //airportsprog_1(argp->host);	
	}
	// printf("Found %s, lat:%f lon:%f\n", merge, search_result->latitude, search_result->longitude);		

	return &result;
}


