/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _PLACES_H_RPCGEN
#define _PLACES_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


typedef struct placesnode *placeslist;

struct placesnode {
	char *code;
	char *name;
	char *state;
	float distance;
	placeslist next;
};
typedef struct placesnode placesnode;

struct location {
	char *city;
	char *state;
	char *host;
};
typedef struct location location;

struct readplaces_ret {
	int err;
	union {
		placeslist list;
	} readplaces_ret_u;
};
typedef struct readplaces_ret readplaces_ret;

#define PLACESPROG 0x3777777D
#define PLACES_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define get_places 1
extern  readplaces_ret * get_places_1(struct location *, CLIENT *);
extern  readplaces_ret * get_places_1_svc(struct location *, struct svc_req *);
extern int placesprog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define get_places 1
extern  readplaces_ret * get_places_1();
extern  readplaces_ret * get_places_1_svc();
extern int placesprog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_placeslist (XDR *, placeslist*);
extern  bool_t xdr_placesnode (XDR *, placesnode*);
extern  bool_t xdr_location (XDR *, location*);
extern  bool_t xdr_readplaces_ret (XDR *, readplaces_ret*);

#else /* K&R C */
extern bool_t xdr_placeslist ();
extern bool_t xdr_placesnode ();
extern bool_t xdr_location ();
extern bool_t xdr_readplaces_ret ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_PLACES_H_RPCGEN */
