/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "places.h"

bool_t
xdr_placestype (XDR *xdrs, placestype *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, objp, MAXLEN))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_placesnum (XDR *xdrs, placesnum *objp)
{
	register int32_t *buf;

	 if (!xdr_array (xdrs, (char **)&objp->placesnum_val, (u_int *) &objp->placesnum_len, MAXLEN,
		sizeof (float), (xdrproc_t) xdr_float))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_placeslist (XDR *xdrs, placeslist *objp)
{
	register int32_t *buf;

	 if (!xdr_pointer (xdrs, (char **)objp, sizeof (struct placesnode), (xdrproc_t) xdr_placesnode))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_placesnode (XDR *xdrs, placesnode *objp)
{
	register int32_t *buf;

	 if (!xdr_placestype (xdrs, &objp->code))
		 return FALSE;
	 if (!xdr_placestype (xdrs, &objp->name))
		 return FALSE;
	 if (!xdr_placestype (xdrs, &objp->state))
		 return FALSE;
	 if (!xdr_placesnum (xdrs, &objp->distance))
		 return FALSE;
	 if (!xdr_placeslist (xdrs, &objp->next))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_location (XDR *xdrs, location *objp)
{
	register int32_t *buf;

	 if (!xdr_placestype (xdrs, &objp->city))
		 return FALSE;
	 if (!xdr_placestype (xdrs, &objp->state))
		 return FALSE;
	 if (!xdr_placestype (xdrs, &objp->host))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_readplaces_ret (XDR *xdrs, readplaces_ret *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->err))
		 return FALSE;
	switch (objp->err) {
	case 0:
		 if (!xdr_placeslist (xdrs, &objp->readplaces_ret_u.list))
			 return FALSE;
		break;
	case 1:
		break;
	default:
		return FALSE;
	}
	return TRUE;
}
