/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "placesairports.h"
#include "trie.h"

airportslist airportsprog_1(coordinates * coord, char *host)
{
  CLIENT *clnt;
  readairports_ret  *result_1;
  struct coordinates  get_airports_1_arg;
  airportslist list;
  
#ifndef DEBUG
  clnt = clnt_create (host, AIRPORTSPROG, AIRPORTS_VERS, "udp");
  if (clnt == NULL) {
	clnt_pcreateerror (host);
	exit (1);
  }
#endif  /* DEBUG */

  result_1 = get_airports_1(coord, clnt);
  if (result_1 == (readairports_ret *) NULL) {
	clnt_perror (clnt, "call failed");
  }
  
  list = result_1->readairports_ret_u.list;
    
  return list;
  
#ifndef DEBUG
  clnt_destroy (clnt);
#endif   /* DEBUG */
}

//:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
//:: This function takes in the state and city and searches the Trie
//:: structure for the location using the possibility of partial
//:: matches. Once the place is found it's latitude and longitude
//:: are sent to the airport_server. The nearest airports are then
//:: returned and then we build a list of the nearest aiport's info
//:: so we can return it back to the client.
//:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::

readplaces_ret *
get_places_1_svc(struct location *argp, struct svc_req *rqstp)
{
	static readplaces_ret  result;
	trieNode_t *search_result;
	char merge[255];
	int i = 0;
		
	// Merge state and city name into a single string (state|city) then convert whole string to lower case
	strcpy(merge, argp->state);
	strcat(merge, argp->city);
	for (i = 0; merge[i]; i++)
	{
	  merge[i] = tolower(merge[i]);
	}

	// Search Trie for place match, allow patial matches
	search_result = TrieSearchPartial(root->children,merge);

	xdr_free((xdrproc_t)xdr_readplaces_ret, (char *)&result);	


	airportslist al;
    placeslist head = NULL;
	placesnode * temp;	
	placeslist * list;

	// found places now make a call to airport_server
	if (search_result) {
	  coordinates *coord = malloc(sizeof *coord);
	  coord->lattitude = search_result->latitude;
	  coord->longitude = search_result->longitude;

	  // get nearest airports
	  al = airportsprog_1(coord, argp->host);
	  
	  // Build list of nearest airport information
	  while (al != NULL) {
		temp = (placesnode *)malloc(sizeof(placesnode));
		temp->code = al->code;
		temp->name = al->name;
		temp->state = al->state;
		temp->distance = al->distance;
		if (head == NULL) {
		  head = temp;
		  head->next = NULL;
		} else {
		  temp->next = head;
		  head = temp;
		}
		al = al->next;
	  }
	  	  
	  list = &result.readplaces_ret_u.list;
	  *list = head;
	}
	
	return &result;
}